"""
Base Generator class — semua generator inherit dari sini
"""


class BaseGenerator:
    """Abstract base untuk semua script generator"""

    TITLE = "Generator"

    def __init__(self, cli):
        self.cli = cli

    def run(self):
        """Entry point — dipanggil oleh menu"""
        self.cli.header(self.TITLE)
        params = self.collect_params()
        if params is None:
            self.cli.warning("Generator dibatalkan.")
            return
        script = self.generate(params)
        self.cli.print_script(self.TITLE, script)
        self.cli.save_script(self.TITLE, script)

    def collect_params(self):
        """Override: kumpulkan parameter dari user. Return dict atau None untuk cancel."""
        raise NotImplementedError

    def generate(self, params):
        """Override: generate script RouterOS. Return string."""
        raise NotImplementedError

    def _header_comment(self, title, extra_lines=None):
        """Generate header comment block untuk script"""
        lines = [
            f"# ═══════════════════════════════════════════════",
            f"# {title}",
            f"# Generated by MikroTik AutoConfig CLI v1.0",
            f"# ═══════════════════════════════════════════════",
        ]
        if extra_lines:
            for line in extra_lines:
                lines.append(f"# {line}")
            lines.append(f"# ───────────────────────────────────────────────")
        return "\n".join(lines)

    def _mbps_to_bps(self, mbps_str):
        """Convert '10M' atau '10' ke bps string untuk RouterOS"""
        s = str(mbps_str).upper().replace("M", "").replace("K", "")
        return mbps_str  # RouterOS pakai format asli: 10M, 1G, dll

    def _bw_string(self, value, unit="M"):
        """Format bandwidth string: 10M, 1G, 512k, dst"""
        return f"{value}{unit}"
